# Generated by Django 3.0.3 on 2020-05-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_auto_20200503_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
