# Generated by Django 3.0.3 on 2020-05-03 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_auto_20200503_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
